<?php
// $Id$
/**
* @file
* Load Brazil Callback Test Scripts.
*/

include_once('brazil_callbacktest.scripts.inc');

/**
 * Implementation of hook_menu().
 */
function brazil_callbacktest_menu() {
  
  $items['admin/voip/brazil_callbacktest'] = array(
    'title' => 'Brazil Callback Test',
    'page callback' => 'brazil_callbacktest_page',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  ); 
  
  return $items;
}

function brazil_callbacktest_page() {
$headers = array(
  array('data' => t('id'), 'field' => 'id', 'sort' => 'desc'),
  array('data' => t('caller number'), 'field' => 'caller_number'),
  array('data' => t('Answer 1'), 'field' => 'answer1'),
  array('data' => t('Answer 2'), 'field' => 'answer2'),
  array('data' => t('Answer 3'), 'field' => 'answer3'),
  array('data' => t('Answer 4'), 'field' => 'answer4'),
  array('data' => t('Date'), 'field' => 'date'),
  array('data' => t('Time'), 'field' => 'time'),
  '');
  $sql = "SELECT * FROM {brazil_callbacktest} ORDER BY id DESC";
  $limit = 50;
  $result = pager_query($sql, $limit);
  
  if($result){
    //your basic while loop to get the data
    while($tmp = db_fetch_array($result)) {
      $answers = unserialize($tmp['answers']);
      $data[] = array(
        'id' => $tmp['id'],
        'caller_number' => $tmp['caller_number'],
        'answer1' => $answers['answer1'],
        'answer2' => $answers['answer2'],
        'answer3' => $answers['answer3'],
        'answer4' => $answers['answer4'],
        'date' => date('m/d/Y', $tmp['timestamp']),
        'time' => date('h:i:s A', $tmp['timestamp']),
      );
    }
  }
  $output .= theme('table', $headers, $data);
  $output .= theme('pager', NULL, $limit, 0);
  return $output;
}
